---
- name: Test connection to remote boxes.
  hosts: "{{ _hosts | default('all') }}"
  gather_facts: false
  become: false


  tasks:
  # Fix tissue 01
  #Added comment
    - name: Ensure server is up
      ansible.builtin.ping:
